[project]
name = "knotrack"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
knotrack = "knotrack.cli:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.12.14,<0.13"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "--basetemp=.pytest_tmp"